[env]
_.file = { path = "~/.env", redact = true }

[settings]
experimental = true # enable experimental features
env_file = ".env"

[tools]
"usage" = "latest"
## https://github.com/1pkg/gopium/releases
"go:github.com/1pkg/gopium" = "latest"
## https://github.com/pulumi/pulumi/releases
"pulumi" = "3"
## https://github.com/sigstore/cosign/releases
"github:sigstore/cosign" = { version = "latest", exe = "cosign-linux-amd64", rename_exe = "cosign" }
## https://github.com/slsa-framework/slsa-verifier
"github:slsa-framework/slsa-verifier" = { version = "latest", exe = "slsa-verifier-linux-amd64", rename_exe = "slsa-verifier" }
## https://github.com/a-h/templ/releases
"aqua:a-h/templ" = '0'
## https://github.com/fluxcd/flux2/releases
"flux2" = "2"
## https://github.com/oven-sh/bun/releases
"bun" = "1"
## https://github.com/rakyll/hey/releases
"go:github.com/rakyll/hey" = "latest"
## https://github.com/sharkdp/hyperfine/releases
"hyperfine" = "latest"
## https://pkg.go.dev/golang.org/x/tools
"go:golang.org/x/tools/cmd/deadcode" = "latest"
## https://github.com/goreleaser/goreleaser/releases
"goreleaser" = "latest"
## https://github.com/nektos/act/releases
"act" = "latest"
