# Configuration file for HyDE
# Environment variables should be on top
# Add your custom configuration in '~/.config/hyde/config.toml'

"$schema" = "./schema.json"

WARP_ENABLE_WAYLAND = 1


[wallpaper]
custom_paths = [
    "$HOME/Pictures/Wallpapers",
] # List of paths to search for wallpapers
backend = "swww" # Wallpaper backend, example: swww, hyprpaper, pcmanfm, feh, etc.

[wallpaper.swww]
# swwwallselect.sh configuration
framerate = 60 # transition framerate
duration = 1   # transition duration
# Transition type [ none | simple | fade | left | right | top | bottom | wipe | wave | grow | center | any | outer | random ]
transition_next = "grow"    # transition type for next wallpaper
transition_prev = "outer"   # transition type for previous wallpaper
transition_default = "grow" # transition type for default wallpaper


# NOTE: 
# for [rofi.*] 
# style <--script's built-in styles, also accepts themes from rofi-theme-selector

[rofi]
# global rofi configuration`
scale = 10 # rofi default scaling

[rofi.hyprlock]
# 'hyprlock.sh select' configuration
scale = 10

[rofi.animation]
# ' animation.sh select' configuration
scale = 8

[rofi.glyph]
# glyph-picker.sh configuration
scale = 8

[rofi.launch]
# rofilaunch.sh configuration
# style = "10"
scale = 5

[rofi.cliphist]
# cliphist.sh configuration
scale = 8

[rofi.wallpaper]
#swwwallselect.sh configuration
scale = 8

[rofi.emoji]
# emoji-picker.sh configuration
style = 2
scale = 8

[rofi.theme]
# themeselect.sh configuration
scale = 6

[wlogout]
style = 2

[battery.notify]
# batterynotify.sh configuration
timer = 120
notify = 1140
interval = 5
dock = true

[battery.notify.threshold]
full = 90
critical = 10
low = 20
unplug = 80


[battery.notify.execute]
unplug = ""
low = ""
critical = "systemctl suspend"
charging = ""
discharging = ""

[keybind.hint]
# keybind.hint.py configuration


[rofi.keybind.hint]
# keybind_hint.sh configuration
delimiter = "\t"
width = "40em"
height = "40em"
line = 16

[screenshot]
# screenshot.sh configuration
annotation_tool = "swappy" # Annotation tool
annotation_pre_command = [
    # 'shader=$(hyprshade current) && hyprshade off && trap restore_shader EXIT', # Use this when you're using hyprshade
] # Pre command for annotation tool
annotation_post_command = [
    # "[ -n \"\\$shader\" ] && hyprshade on \\$shader", # Use this when you're using hyprshade
    "",
] # Post command for annotation tool


[rofi.bookmark]
file = "$HOME/.config/hyde/bookmarks.lst"

[rofi.search]
file = "$HOME/.config/hyde/search.lst"


[wallbash]
skip_template = [
    "",
]    # skips the template when using wallbash. Requires full path to the template

[waybar]
font = "JetBrainsMono Nerd Font"
scale=30                                # total scaling
# output = ["", ""]                     # Default monitor output for waybar

[weather]
temperature_unit='c'	# Temperature unit to Â°C or Â°F ('c' or 'f')
time_format='24h'		# Time format ('12h or 24h')
windspeed_unit='km/h'	# Windspeed unit ('kh/h' or 'mph')
show_icon= true			# Show the weather icon in waybar
show_location= true	    # Show the location in waybar
show_today= true		# Detailed description of today in tooltip
forecast_days= 3 		# Number of days to show forecast (0-3)
location = ''			# Location/coordinates string for the weather output

[cava.stdout]
# 'cava.sh stdout' configuration
max_instances = 1 # Maximum number of cava instances // fix and workaround when a process won't kill 'cava ' process
bar = "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆ"
width = 20
range = 7         # Number of (bars -1)
standby = "ðŸŽ¶"

[cava.hyprlock]
# 'cava.sh hyprlock' configuration
max_instances = 1 # Maximum number of cava instances // fix and workaround when a process won't kill 'cava ' process
bar = "ðŸŒ‘ðŸŒ’ðŸŒ“ðŸŒ”ðŸŒ•ðŸŒ–ðŸŒ—ðŸŒ˜"
width = 20
range = 7
standby = "ðŸŽ¶"

[cava.waybar]
# 'cava.sh waybar' configuration
max_instances = 1 # Maximum number of cava instances // fix and workaround when waybar won't kill 'cava ' process
bar = "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆ"
width = 20
range = 7
standby = "ðŸŽ¶"


[hypr.config]
# List of regex to sanitize in the theme.config // Useful for deprecated options to be removed from the theme.config
sanitize = [
    '.*rgba\(.*,*,*,*,',
] # Remove all rgba colors // workarounds for rgba colors crashing hyprland

[volume]
# volumecontrol.sh configuration
notify = true # Useful for systems that have their own OSD
steps = 5     # Number of steps to increase/decrease volume
boost = false # Enable volume boost
boost_limit = 150 # Volume boost limit // Don't kill your ears/speakers

[brightness]
# brightnesscontrol.sh configuration
notify = true # Useful for systems that have their own OSD
steps = 5     # Number of steps to increase/decrease brightness


[sysmonitor]
#  sysmonlaunch.sh configuration // System monitor configuration
execute = "btop"                   # Default command to execute // accepts executable or app.desktop
commands = ["btop", "htop", "top"] # Fallback command options


[notification]
# notification script can use this configuration
font = "mononoki Nerd Font"         # Font for notifications
font_size = 8                     # Font size for notifications
